### PR TITLE
Implementing chef

### PR DESCRIPTION
**Pull request by SamuelDavis**
Standardizing machine with chef also floating div went away

REQUIRES BERKSHELF NOW

### CODE REVIEW

**Comment by SamuelDavis** [comment]
@sudo-reboot Dude how great is this PR? You tell me.

**Comment by SamuelDavis** [comment]
@sugarPhlox Hey Cara, deme mas cake sivousplait

**Comment by TomWoodward** [comment]
:cake:

**Comment by sugarPhlox** [comment]
It's s'il vous plaît. 

:cake:

**Pull request merged**
