### PR TITLE
Corrected/added grammar, changed certain verbiage

### PR DESCRIPTION
**Pull request by noelseph**
Fixed mistakes I had made. Added in punctuation where it was missing. Switched up some syntax and changed some "."s to "!" to actually make it look like we're excited about this.

### CODE REVIEW

**Comment by avophile** [comment]
I'm not sure adding the "Oxford Comma" in the "The Name" section fits with site's kewl voice.

**Comment by noelseph** [comment]
Maybe I should have asked this prior, but what's our intended audience with Lavender? Younger designers/devs, current professionals? I always kinda err on the side of professional > kewl, but I could be in the wrong here.

**Comment by sugarPhlox** [comment]
Younger crowd of professionals. People looking for an upgrade, or more handling from a language like Jade.

**Comment by noelseph** [comment]
This right here is why I think the Oxford comma is useful, and sometimes necessary.
https://i.imgur.com/bn2hf3Q.jpg

**Comment by avophile** [comment]
Yeah, but:

"The point is simply to write clearly or, as the old fumblerule goes, “Eschew obfuscation. Espouse elucidation.” If one comma or lack thereof creates ambiguity in your writing, then you lack either the imagination or ambition to change your syntax."

from: http://www.neboagency.com/blog/a-comma-misconception/

The Lavender website text under consideration mitigates the potential confusion otherwise addressed by an Oxford comma by virtue of being an enumerated list. The enumeration allows the reader to infer the proper relationship:

"Jade is three things: a color, an item and a programming language."

This is perfectly clear. 

"Jade is three things: a color, an item, and a programming language."

Too many punctuations!

Also, your comment above arguably exemplifies a compound predicate with a redundant comma.

"This right here is why I think the Oxford comma is useful, and sometimes necessary."

But, let's let that one slide since, grammar notwithstanding, it's all about your personal, writing style.

**Comment by noelseph** [comment]
I suppose it is ingrained in me to separate my independent/dependent clauses as such. It's the way I taught my 9th graders to do it, as well. I find that it reads/scans easier/better. As you said, it is mostly style. More so, it really isn't a make or break issue. The difference between cats and sentences? Sentences have pause at the end of the clause, and cats have claws at the end of their paws. If enough people dislike the look of the comma, it can be murdered and I won't be upset :-P

**Pull request closed without merging**
